// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManager.Models.EfCore;

#nullable disable

namespace ProductManager.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20230630185436_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductManager.Models.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("Stok")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PRZKÇ2L",
                            Name = "Porçöz Kireç Çözücü 2 L",
                            Price = 54.90m,
                            Stok = 50
                        },
                        new
                        {
                            Id = 2,
                            Code = "CNGBTR45",
                            Name = "Eti Canga Bitter 45 G",
                            Price = 6m,
                            Stok = 253
                        },
                        new
                        {
                            Id = 3,
                            Code = "TCRCHS450",
                            Name = "Taciroğlu Koyun Peynir 3 Dilimli 450 G\r\n",
                            Price = 115.90m,
                            Stok = 176
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
